# Generated by Django 4.0.6 on 2023-08-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.ManyToManyField(to='core.project'),
        ),
    ]
