# Generated by Django 4.0.6 on 2023-08-08 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_client_paid_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email_of_paid_account',
        ),
        migrations.RemoveField(
            model_name='client',
            name='login_of',
        ),
        migrations.RemoveField(
            model_name='client',
            name='login_of_paid_account',
        ),
        migrations.RemoveField(
            model_name='client',
            name='of_email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='of_password_email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='paid_account',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password_of',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password_of_email_paid_account',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password_of_paid_account',
        ),
        migrations.RemoveField(
            model_name='client',
            name='telegram_photos_link',
        ),
    ]
