# Generated by Django 4.0.6 on 2023-08-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_client_email_of_paid_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='project_info',
            field=models.JSONField(default={'AnastasiaDating': [], 'CharmDate': [], 'DateMe': [], 'Fansly': [], 'GoldenBride': [], 'Jump4Love': [], 'OnlyFans': []}),
        ),
        migrations.AddField(
            model_name='client',
            name='socials',
            field=models.JSONField(default={'Facebook': [], 'Instagram': [], 'Reddit': []}),
        ),
    ]
