version: "3.9"

services:
  backend:
    container_name: heaven_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/heaven
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - db
    networks:
      - database

  db:
    container_name: heaven_database
    image: postgis/postgis
    ports:
      - "127.0.0.1:15432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - database

networks:
  database:
