# Generated by Django 4.0.6 on 2023-08-11 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(choices=[('OF', 'OnlyFans'), ('AD', 'AnastasiaDating'), ('DM', 'DateMe'), ('CD', 'CharmDate'), ('J4', 'JumpForLove'), ('GB', 'GoldenBride'), ('RM', 'RomansCompass'), ('PM', 'PrimeDate'), ('F', 'Fansly')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(default='01-01-2023')),
                ('table_type', models.CharField(choices=[('OP', 'OnlyFans'), ('FP', 'FreeAccOnlyfans'), ('PP', 'PayAccOnlyfans'), ('AD', 'AnastasiaDating'), ('D', 'Dating')], max_length=50, null=True)),
                ('account_id', models.CharField(max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.client')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('data', models.FloatField(null=True)),
                ('is_day_off', models.BooleanField(default=False)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.table')),
            ],
        ),
    ]
